# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/anime-royale/anime-royale

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/anime-royale/anime-royale/build-wasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/anime-royale/anime-royale/build-wasm/CMakeFiles /home/runner/work/anime-royale/anime-royale/build-wasm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/anime-royale/anime-royale/build-wasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named anime-royale

# Build rule for target.
anime-royale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 anime-royale
.PHONY : anime-royale

# fast build rule for target.
anime-royale/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/build
.PHONY : anime-royale/fast

src/core/camera.o: src/core/camera.c.o
.PHONY : src/core/camera.o

# target to build an object file
src/core/camera.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/camera.c.o
.PHONY : src/core/camera.c.o

src/core/camera.i: src/core/camera.c.i
.PHONY : src/core/camera.i

# target to preprocess a source file
src/core/camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/camera.c.i
.PHONY : src/core/camera.c.i

src/core/camera.s: src/core/camera.c.s
.PHONY : src/core/camera.s

# target to generate assembly for a file
src/core/camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/camera.c.s
.PHONY : src/core/camera.c.s

src/core/game.o: src/core/game.c.o
.PHONY : src/core/game.o

# target to build an object file
src/core/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/game.c.o
.PHONY : src/core/game.c.o

src/core/game.i: src/core/game.c.i
.PHONY : src/core/game.i

# target to preprocess a source file
src/core/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/game.c.i
.PHONY : src/core/game.c.i

src/core/game.s: src/core/game.c.s
.PHONY : src/core/game.s

# target to generate assembly for a file
src/core/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/game.c.s
.PHONY : src/core/game.c.s

src/core/gameobject.o: src/core/gameobject.c.o
.PHONY : src/core/gameobject.o

# target to build an object file
src/core/gameobject.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/gameobject.c.o
.PHONY : src/core/gameobject.c.o

src/core/gameobject.i: src/core/gameobject.c.i
.PHONY : src/core/gameobject.i

# target to preprocess a source file
src/core/gameobject.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/gameobject.c.i
.PHONY : src/core/gameobject.c.i

src/core/gameobject.s: src/core/gameobject.c.s
.PHONY : src/core/gameobject.s

# target to generate assembly for a file
src/core/gameobject.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/gameobject.c.s
.PHONY : src/core/gameobject.c.s

src/core/go_pool.o: src/core/go_pool.c.o
.PHONY : src/core/go_pool.o

# target to build an object file
src/core/go_pool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/go_pool.c.o
.PHONY : src/core/go_pool.c.o

src/core/go_pool.i: src/core/go_pool.c.i
.PHONY : src/core/go_pool.i

# target to preprocess a source file
src/core/go_pool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/go_pool.c.i
.PHONY : src/core/go_pool.c.i

src/core/go_pool.s: src/core/go_pool.c.s
.PHONY : src/core/go_pool.s

# target to generate assembly for a file
src/core/go_pool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/go_pool.c.s
.PHONY : src/core/go_pool.c.s

src/core/input.o: src/core/input.c.o
.PHONY : src/core/input.o

# target to build an object file
src/core/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/input.c.o
.PHONY : src/core/input.c.o

src/core/input.i: src/core/input.c.i
.PHONY : src/core/input.i

# target to preprocess a source file
src/core/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/input.c.i
.PHONY : src/core/input.c.i

src/core/input.s: src/core/input.c.s
.PHONY : src/core/input.s

# target to generate assembly for a file
src/core/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/input.c.s
.PHONY : src/core/input.c.s

src/core/time.o: src/core/time.c.o
.PHONY : src/core/time.o

# target to build an object file
src/core/time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/time.c.o
.PHONY : src/core/time.c.o

src/core/time.i: src/core/time.c.i
.PHONY : src/core/time.i

# target to preprocess a source file
src/core/time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/time.c.i
.PHONY : src/core/time.c.i

src/core/time.s: src/core/time.c.s
.PHONY : src/core/time.s

# target to generate assembly for a file
src/core/time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/time.c.s
.PHONY : src/core/time.c.s

src/core/vector2.o: src/core/vector2.c.o
.PHONY : src/core/vector2.o

# target to build an object file
src/core/vector2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/vector2.c.o
.PHONY : src/core/vector2.c.o

src/core/vector2.i: src/core/vector2.c.i
.PHONY : src/core/vector2.i

# target to preprocess a source file
src/core/vector2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/vector2.c.i
.PHONY : src/core/vector2.c.i

src/core/vector2.s: src/core/vector2.c.s
.PHONY : src/core/vector2.s

# target to generate assembly for a file
src/core/vector2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/vector2.c.s
.PHONY : src/core/vector2.c.s

src/game/ar_controller.o: src/game/ar_controller.c.o
.PHONY : src/game/ar_controller.o

# target to build an object file
src/game/ar_controller.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/ar_controller.c.o
.PHONY : src/game/ar_controller.c.o

src/game/ar_controller.i: src/game/ar_controller.c.i
.PHONY : src/game/ar_controller.i

# target to preprocess a source file
src/game/ar_controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/ar_controller.c.i
.PHONY : src/game/ar_controller.c.i

src/game/ar_controller.s: src/game/ar_controller.c.s
.PHONY : src/game/ar_controller.s

# target to generate assembly for a file
src/game/ar_controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/ar_controller.c.s
.PHONY : src/game/ar_controller.c.s

src/game/gameobjects/bg_renderer.o: src/game/gameobjects/bg_renderer.c.o
.PHONY : src/game/gameobjects/bg_renderer.o

# target to build an object file
src/game/gameobjects/bg_renderer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/bg_renderer.c.o
.PHONY : src/game/gameobjects/bg_renderer.c.o

src/game/gameobjects/bg_renderer.i: src/game/gameobjects/bg_renderer.c.i
.PHONY : src/game/gameobjects/bg_renderer.i

# target to preprocess a source file
src/game/gameobjects/bg_renderer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/bg_renderer.c.i
.PHONY : src/game/gameobjects/bg_renderer.c.i

src/game/gameobjects/bg_renderer.s: src/game/gameobjects/bg_renderer.c.s
.PHONY : src/game/gameobjects/bg_renderer.s

# target to generate assembly for a file
src/game/gameobjects/bg_renderer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/bg_renderer.c.s
.PHONY : src/game/gameobjects/bg_renderer.c.s

src/game/gameobjects/camera_controller.o: src/game/gameobjects/camera_controller.c.o
.PHONY : src/game/gameobjects/camera_controller.o

# target to build an object file
src/game/gameobjects/camera_controller.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/camera_controller.c.o
.PHONY : src/game/gameobjects/camera_controller.c.o

src/game/gameobjects/camera_controller.i: src/game/gameobjects/camera_controller.c.i
.PHONY : src/game/gameobjects/camera_controller.i

# target to preprocess a source file
src/game/gameobjects/camera_controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/camera_controller.c.i
.PHONY : src/game/gameobjects/camera_controller.c.i

src/game/gameobjects/camera_controller.s: src/game/gameobjects/camera_controller.c.s
.PHONY : src/game/gameobjects/camera_controller.s

# target to generate assembly for a file
src/game/gameobjects/camera_controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/camera_controller.c.s
.PHONY : src/game/gameobjects/camera_controller.c.s

src/game/gameobjects/cursor.o: src/game/gameobjects/cursor.c.o
.PHONY : src/game/gameobjects/cursor.o

# target to build an object file
src/game/gameobjects/cursor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/cursor.c.o
.PHONY : src/game/gameobjects/cursor.c.o

src/game/gameobjects/cursor.i: src/game/gameobjects/cursor.c.i
.PHONY : src/game/gameobjects/cursor.i

# target to preprocess a source file
src/game/gameobjects/cursor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/cursor.c.i
.PHONY : src/game/gameobjects/cursor.c.i

src/game/gameobjects/cursor.s: src/game/gameobjects/cursor.c.s
.PHONY : src/game/gameobjects/cursor.s

# target to generate assembly for a file
src/game/gameobjects/cursor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/cursor.c.s
.PHONY : src/game/gameobjects/cursor.c.s

src/game/gameobjects/player.o: src/game/gameobjects/player.c.o
.PHONY : src/game/gameobjects/player.o

# target to build an object file
src/game/gameobjects/player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/player.c.o
.PHONY : src/game/gameobjects/player.c.o

src/game/gameobjects/player.i: src/game/gameobjects/player.c.i
.PHONY : src/game/gameobjects/player.i

# target to preprocess a source file
src/game/gameobjects/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/player.c.i
.PHONY : src/game/gameobjects/player.c.i

src/game/gameobjects/player.s: src/game/gameobjects/player.c.s
.PHONY : src/game/gameobjects/player.s

# target to generate assembly for a file
src/game/gameobjects/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/player.c.s
.PHONY : src/game/gameobjects/player.c.s

src/game/gameobjects/weapons/basic_bullet.o: src/game/gameobjects/weapons/basic_bullet.c.o
.PHONY : src/game/gameobjects/weapons/basic_bullet.o

# target to build an object file
src/game/gameobjects/weapons/basic_bullet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/basic_bullet.c.o
.PHONY : src/game/gameobjects/weapons/basic_bullet.c.o

src/game/gameobjects/weapons/basic_bullet.i: src/game/gameobjects/weapons/basic_bullet.c.i
.PHONY : src/game/gameobjects/weapons/basic_bullet.i

# target to preprocess a source file
src/game/gameobjects/weapons/basic_bullet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/basic_bullet.c.i
.PHONY : src/game/gameobjects/weapons/basic_bullet.c.i

src/game/gameobjects/weapons/basic_bullet.s: src/game/gameobjects/weapons/basic_bullet.c.s
.PHONY : src/game/gameobjects/weapons/basic_bullet.s

# target to generate assembly for a file
src/game/gameobjects/weapons/basic_bullet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/basic_bullet.c.s
.PHONY : src/game/gameobjects/weapons/basic_bullet.c.s

src/game/gameobjects/weapons/pistol.o: src/game/gameobjects/weapons/pistol.c.o
.PHONY : src/game/gameobjects/weapons/pistol.o

# target to build an object file
src/game/gameobjects/weapons/pistol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/pistol.c.o
.PHONY : src/game/gameobjects/weapons/pistol.c.o

src/game/gameobjects/weapons/pistol.i: src/game/gameobjects/weapons/pistol.c.i
.PHONY : src/game/gameobjects/weapons/pistol.i

# target to preprocess a source file
src/game/gameobjects/weapons/pistol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/pistol.c.i
.PHONY : src/game/gameobjects/weapons/pistol.c.i

src/game/gameobjects/weapons/pistol.s: src/game/gameobjects/weapons/pistol.c.s
.PHONY : src/game/gameobjects/weapons/pistol.s

# target to generate assembly for a file
src/game/gameobjects/weapons/pistol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/pistol.c.s
.PHONY : src/game/gameobjects/weapons/pistol.c.s

src/game/gameobjects/weapons/shotgun.o: src/game/gameobjects/weapons/shotgun.c.o
.PHONY : src/game/gameobjects/weapons/shotgun.o

# target to build an object file
src/game/gameobjects/weapons/shotgun.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/shotgun.c.o
.PHONY : src/game/gameobjects/weapons/shotgun.c.o

src/game/gameobjects/weapons/shotgun.i: src/game/gameobjects/weapons/shotgun.c.i
.PHONY : src/game/gameobjects/weapons/shotgun.i

# target to preprocess a source file
src/game/gameobjects/weapons/shotgun.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/shotgun.c.i
.PHONY : src/game/gameobjects/weapons/shotgun.c.i

src/game/gameobjects/weapons/shotgun.s: src/game/gameobjects/weapons/shotgun.c.s
.PHONY : src/game/gameobjects/weapons/shotgun.s

# target to generate assembly for a file
src/game/gameobjects/weapons/shotgun.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/shotgun.c.s
.PHONY : src/game/gameobjects/weapons/shotgun.c.s

src/game/gameobjects/weapons/weapon.o: src/game/gameobjects/weapons/weapon.c.o
.PHONY : src/game/gameobjects/weapons/weapon.o

# target to build an object file
src/game/gameobjects/weapons/weapon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/weapon.c.o
.PHONY : src/game/gameobjects/weapons/weapon.c.o

src/game/gameobjects/weapons/weapon.i: src/game/gameobjects/weapons/weapon.c.i
.PHONY : src/game/gameobjects/weapons/weapon.i

# target to preprocess a source file
src/game/gameobjects/weapons/weapon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/weapon.c.i
.PHONY : src/game/gameobjects/weapons/weapon.c.i

src/game/gameobjects/weapons/weapon.s: src/game/gameobjects/weapons/weapon.c.s
.PHONY : src/game/gameobjects/weapons/weapon.s

# target to generate assembly for a file
src/game/gameobjects/weapons/weapon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/gameobjects/weapons/weapon.c.s
.PHONY : src/game/gameobjects/weapons/weapon.c.s

src/game/main.o: src/game/main.c.o
.PHONY : src/game/main.o

# target to build an object file
src/game/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/main.c.o
.PHONY : src/game/main.c.o

src/game/main.i: src/game/main.c.i
.PHONY : src/game/main.i

# target to preprocess a source file
src/game/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/main.c.i
.PHONY : src/game/main.c.i

src/game/main.s: src/game/main.c.s
.PHONY : src/game/main.s

# target to generate assembly for a file
src/game/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anime-royale.dir/build.make CMakeFiles/anime-royale.dir/src/game/main.c.s
.PHONY : src/game/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... anime-royale"
	@echo "... core"
	@echo "... src/core/camera.o"
	@echo "... src/core/camera.i"
	@echo "... src/core/camera.s"
	@echo "... src/core/game.o"
	@echo "... src/core/game.i"
	@echo "... src/core/game.s"
	@echo "... src/core/gameobject.o"
	@echo "... src/core/gameobject.i"
	@echo "... src/core/gameobject.s"
	@echo "... src/core/go_pool.o"
	@echo "... src/core/go_pool.i"
	@echo "... src/core/go_pool.s"
	@echo "... src/core/input.o"
	@echo "... src/core/input.i"
	@echo "... src/core/input.s"
	@echo "... src/core/time.o"
	@echo "... src/core/time.i"
	@echo "... src/core/time.s"
	@echo "... src/core/vector2.o"
	@echo "... src/core/vector2.i"
	@echo "... src/core/vector2.s"
	@echo "... src/game/ar_controller.o"
	@echo "... src/game/ar_controller.i"
	@echo "... src/game/ar_controller.s"
	@echo "... src/game/gameobjects/bg_renderer.o"
	@echo "... src/game/gameobjects/bg_renderer.i"
	@echo "... src/game/gameobjects/bg_renderer.s"
	@echo "... src/game/gameobjects/camera_controller.o"
	@echo "... src/game/gameobjects/camera_controller.i"
	@echo "... src/game/gameobjects/camera_controller.s"
	@echo "... src/game/gameobjects/cursor.o"
	@echo "... src/game/gameobjects/cursor.i"
	@echo "... src/game/gameobjects/cursor.s"
	@echo "... src/game/gameobjects/player.o"
	@echo "... src/game/gameobjects/player.i"
	@echo "... src/game/gameobjects/player.s"
	@echo "... src/game/gameobjects/weapons/basic_bullet.o"
	@echo "... src/game/gameobjects/weapons/basic_bullet.i"
	@echo "... src/game/gameobjects/weapons/basic_bullet.s"
	@echo "... src/game/gameobjects/weapons/pistol.o"
	@echo "... src/game/gameobjects/weapons/pistol.i"
	@echo "... src/game/gameobjects/weapons/pistol.s"
	@echo "... src/game/gameobjects/weapons/shotgun.o"
	@echo "... src/game/gameobjects/weapons/shotgun.i"
	@echo "... src/game/gameobjects/weapons/shotgun.s"
	@echo "... src/game/gameobjects/weapons/weapon.o"
	@echo "... src/game/gameobjects/weapons/weapon.i"
	@echo "... src/game/gameobjects/weapons/weapon.s"
	@echo "... src/game/main.o"
	@echo "... src/game/main.i"
	@echo "... src/game/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

