name: Build and Deploy

on:
  workflow_dispatch:

env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libsdl2-dev libsdl2-image-dev

      - name: Build rcds
        run: |
          git clone https://github.com/romilk-senpai/rcds.git
          cd rcds
          make static-wasm
          cd ..
          cp -r rcds/librcds-wasm .

      - name: Build anime-royale
        run: |
          make build-wasm-test
          make build-wasm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build-wasm
